### PR TITLE
Heading class

### PR DESCRIPTION
**Pull request by Solinx**
Allow developers to add a custom class to a "heading" element

### CODE REVIEW

**Comment by devinsays** [comment]
Hi. Thanks for the pull request!

Each heading already has a unique class. Can you explain your use case for requiring the additional flexibility?

**Comment by Solinx** [comment]
Hi Devin,

We could use it to add the class "hidden". This allows elements to be hidden without having to add any custom css styling. I was actually looking into the possibility of hiding an entire tab, but had to quickly move on to other tasks before I could finish. 

Our use case is that we have a plugin with various features that can be enabled upon request. Those features sometimes have additional settings. We'd like to show those in a separate tab and only show this tab if the feature for which the settings are is enabled. If we'd conditionally add the tab depending on the state of the feature we'd loose the settings as soon as the feature is turned off, so we have to hide the tab instead.

Regards,
Wouter van Dam

**Comment by Solinx** [comment]
Hi Devin,

I've had the chance to look at the code again and noticed that my change causes a problem, being that the space I add to separate the custom class is removed by the regex on line 402. Do you want to allow spaces in the regex? Or do you want to add the custom class after the regex? And if so, do you want the custom class(es) to go through a regex as well?

Also, it appears that the effect I aim for can be fully achieved by applying very similar changes at lines 25 to 27.

Regards,
Wouter van Dam

**Comment by devinsays** [comment]
Hi Wouter. You should be able to achieve your goal by conditionally loading the tab or option set via PHP. Once an option is saved/updated it persists in the database until it's deleted or modified again.

**Comment by Solinx** [comment]
Hi Devin,

Thanks for the suggestion. I tried that solution some time ago, but unfortunately it did not work that way. It's because all options of the options framework are stored into a single WordPress option entry. All fields have to be part of the html at all the time to persist and retain their values. If a field is not part of the html when the options are saved then the field value is effectively removed.

**Comment by devinsays** [comment]
A default should always be used when requesting an option:

of_get_option( $option, $default );

If you do that, it shouldn't matter whether the options have been saved or not. It will also make sure your theme still works if the plugin is disabled and when it is first installed.

**Comment by Solinx** [comment]
True, but that only works when there are defaults. In our case we've got a single plugin that's being used on multiple sites, each with their own set of unique API keys. Some users will be granted access to configure these API keys, while others will only get access to modify less sensitive settings. 

When I only add the fields for the API keys for users with appropriate rights, the keys get removed whenever a user without those rights changes an option.

**Comment by devinsays** [comment]
Ok, got you. Give me some time to look through your pull request, test, and make sure it's something that can roll out to a million installs without causing issues.

**Comment by Solinx** [comment]
Hi Devin,

Thanks! Right now the pull request won't fly. 

"the space I add to separate the custom class is removed by the regex on line 402. Do you want to allow spaces in the regex? Or do you want to add the custom class after the regex? And if so, do you want the custom class(es) to go through a regex as well?

Also, it appears that the effect I aim for can be fully achieved by applying very similar changes at lines 25 to 27."

Which solution do you want?

**Pull request closed without merging**
